package com.example.ataskmanager;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.ataskmanager.DB.AppDataBase;

@Entity(tableName = AppDataBase.TASK_TABLE)
public class Task {

    @PrimaryKey(autoGenerate = true)
    private int mTaskId;

    private String mEvent;
    private String mDate;
    private String mDescription;
    private boolean mCompleted = false;

    private int mUserId;

    public Task(String mEvent, String mDescription, String mDate, int userId) {
        this.mEvent = mEvent;
        this.mDate = mDate;
        this.mDescription = mDescription;
        this.mCompleted = false;
        this.mUserId = userId;
    }



    //AutoGenerated ToString.
    @Override
    public String toString() {
         return "Event: " + mEvent  + "\n" +
                "Description: " + mDescription + "\n" +
                "Date: " + mDate + "\n" +
                "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n";
    }

    //AutoGenerated Getters and Setters Below.

    public int getUserId() {
        return mUserId;
    }

    public void setUserId(int mUserId) {
        this.mUserId = mUserId;
    }

    public String getEvent() {
        return mEvent;
    }

    public void setEvent(String event) {
        this.mEvent = event;
    }

    public String getDate() {
        return mDate;
    }

    public void setDate(String date) {
        this.mDate = date;
    }

    public String getDescription() {
        return mDescription;
    }

    public void setDescription(String description) {
        this.mDescription = description;
    }

    public boolean isCompleted() {
        return mCompleted;
    }

    public void setCompleted(boolean completed) {
        this.mCompleted = completed;
    }

    public int getTaskId() {
        return mTaskId;
    }

    public void setTaskId(int taskId) {
        this.mTaskId = taskId;
    }
}
