package com.example.ataskmanager;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "task_table")
public class Task {

    public Task(String mEvent, String mDate, String mDescription) {
        this.mEvent = mEvent;
        this.mDate = mDate;
        this.mDescription = mDescription;
    }

    @PrimaryKey(autoGenerate = true)
    private int taskId;
    private String mEvent;
    private String mDate;
    private String mDescription;
    private boolean mCompleted = false;





    //AutoGenerated ToString.
    @Override
    public String toString() {
        return "Task{" +
                "mEvent='" + mEvent + '\'' +
                ", mDate='" + mDate + '\'' +
                ", mDescription='" + mDescription + '\'' +
                ", mCompleted=" + mCompleted +
                '}';
    }

    //AutoGenerated Getters and Setters Below.
    public String getEvent() {
        return mEvent;
    }

    public void setEvent(String event) {
        this.mEvent = event;
    }

    public String getDate() {
        return mDate;
    }

    public void setDate(String date) {
        this.mDate = date;
    }

    public String getDescription() {
        return mDescription;
    }

    public void setDescription(String description) {
        this.mDescription = description;
    }

    public boolean isCompleted() {
        return mCompleted;
    }

    public void setCompleted(boolean completed) {
        this.mCompleted = completed;
    }

    public int getTaskId() {
        return taskId;
    }

    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }
}
